### ISSUE TITLE
New package - MenuMeters (OSX)

### ISSUE THREAD

**Issue by Trevoke** [GA-WDI/installfest#35]
[MenuMeters](http://www.ragingmenace.com/software/menumeters/) is a godsend.

![menumeters screenshot](http://www.ragingmenace.com/software/menumeters/MenuMetersMenubar.png)

It looks like that, sits in the top bar in OSX and shows you information like CPU activity, network activity, memory activity.

**Comment by h4w5** [comment]
Possibly this can be added to a list of recommended apps?
