### ISSUE TITLE
Sublime Keybinding for toggling color schemes

### ISSUE THREAD

**Issue by phlco** [GA-WDI/installfest#52]
This may be useful for instructors to toggle color schemes in front of the class or on the projector.

```
// http://www.sublimetext.com/docs/2/settings.html
[
  {
    // Toggle Light Theme
    "keys": ["super+d", "super+l"],
    "command": "set_setting",
    "args":
    {
        "setting": "color_scheme",
        "value": "Packages/Tomorrow Color Schemes/Tomorrow.tmTheme"
    }
  },
  {
    // Toggle Dark Theme
    "keys": ["super+d", "super+k"],
    "command": "set_setting",
    "args":
    {
        "setting": "color_scheme",
        "value": "Packages/Tomorrow Color Schemes/Tomorrow-Night.tmTheme"
    }
  },
  { "keys": ["alt+q"], "command": "wrap_lines", "args": {"width": 80} }
]
```

**Comment by h4w5** [comment]
Actually, I just came across this for trying to toggle the "theme" setting as well as the color scheme. It doesn't work! But there is a package called Themr that allows us to toggle themes as well as color schemes...

**Comment by h4w5** [comment]
@phlco The default install now includes Themr... We should create different themes to toggle between, and there is a single mapped "Toggle Theme" keyword.
